version: "3.8"

services:
  instagrammer_db:
    image: postgres
    volumes:
      - data:/var/lib/postgresql
    env_file:
      - .env.dev
    ports:
      - "5400:5432"
    expose:
      - "5432"

volumes:
  data:
