version: "3.8"

services:
  instagrammer_db:
    image: postgres
    volumes:
      - data:/var/lib/postgresql
    env_file:
      - libs/api/core/config-environment/src/lib/database/postgres.env
    ports:
      - "5432:5432"
    expose:
      - "5432"

volumes:
  data:
