version: "3.8"

services:
  instagrammer_db:
    image: postgres
    volumes:
      - data:/var/lib/postgresql
    env_file:
      - apps/api/src/environments/postgres.env
    ports:
      - "5432:5432"
    expose:
      - "5432"

volumes:
  data:
