export enum EnvironmentVariable {
  POSTGRES_PASSWORD = 'POSTGRES_PASSWORD',
  POSTGRES_USER = 'POSTGRES_USER',
  POSTGRES_DB_NAME = 'POSTGRES_DB_NAME',
  POSTGRES_PORT = 'POSTGRES_PORT',
  POSTGRES_HOST = 'POSTGRES_HOST',
  PASSPORT_SECRET = 'PASSPORT_SECRET',
  PASSPORT_TOKEN_EXPIRES = 'PASSPORT_TOKEN_EXPIRES',
  PASSPORT_STRATEGY = 'PASSPORT_STRATEGY',
  PASSPORT_DEFAULT_STRATEGY = 'PASSPORT_DEFAULT_STRATEGY',
  ACCESS_TOKEN_EXPIRES_IN_SECONDS = 'ACCESS_TOKEN_EXPIRES_IN_SECONDS',
  REFRESH_TOKEN_SHORT_EXPIRES_IN_SECONDS = 'REFRESH_TOKEN_SHORT_EXPIRES_IN_SECONDS',
  REFRESH_TOKEN_LONG_EXPIRES_IN_SECONDS = 'REFRESH_TOKEN_LONG_EXPIRES_IN_SECONDS',
}
