#!/bin/sh

# Font colors
F_RED=$(tput setaf 1)
F_GREEN=$(tput setaf 2)
F_YELLOW=$(tput setaf 3)
F_BLUE=$(tput setaf 4)
F_WHITE=$(tput setaf 7)

# Background colors
B_RED=$(tput setab 1)
B_GREEN=$(tput setab 2)
B_YELLOW=$(tput setab 3)
B_BLUE=$(tput setab 4)
B_WHITE=$(tput setab 7)

# Reset terminal colors
RESET_TERMINAL_COLORS=$(tput sgr0)

if ! head -1 "$1" | grep -qE "/^(feat|fix|docs|init|test|refactor|ci|revert)(\(.+?\))?: (#[1-9]\d*) .{1,}$/g"; then
    echo "${B_WHITE}************************************************${RESET_TERMINAL_COLORS}"
    echo "${B_WHITE}${F_RED}Aborting commit. Your commit message is invalid.${RESET_TERMINAL_COLORS}" >&2
    echo "${B_WHITE}************************************************${RESET_TERMINAL_COLORS}"
    echo "${B_WHITE}${F_BLUE}Correct example:${RESET_TERMINAL_COLORS} ${F_GREEN}feat(scope): #issue_num <commit_msg>${RESET_TERMINAL_COLORS}"
    exit 1
fi

if ! head -1 "$1" | grep -qE "^.{1,88}$"; then
    echo "${F_RED}Aborting commit. Your commit message is too long.${RESET_TERMINAL_COLORS}" >&2
    exit 1
fi
